### ISSUE TITLE
[Question] can't build project, can't find m3.lib

### ISSUE THREAD

**Issue by TianhaoLi** [SakuraEngine/Sakura.Runtime#16]
D:\GitProject\Sakura.Runtime\SDKs>xmake
install: tracyclient-windows-x64.zip
install: dstorage-windows-x64.zip
install: amdags-windows-x64.zip
install: nvapi-windows-x64.zip
install: WinPixEventRuntime-windows-x64.zip
install: SDL2-windows-x64.zip
install: m3-windows-x64.zip
failed to install m3, file m3-windows-x64.zip not found!
install: llfio-windows-x64.zip
[ 35%]: compiling.debug resources\windows\sakura.rc
[ 48%]: compiling.debug resources\windows\sakura.rc
[ 82%]: linking.debug SkrRT.dll
error: LINK : fatal error LNK1104: 无法打开文件“m3.lib”

warning: You are working in the project directory(D:\GitProject\Sakura.Runtime) and you can also
force to build in current directory via run `xmake -P .`
warning: add -v for getting more warnings ..

SDK中 m3-windows-x64.zip  好像没有正确的下载，执行xmake l setup.lua后如图
![image](https://user-images.githubusercontent.com/26623453/186323244-6dcda5eb-6cce-451f-a2dc-ce45167ff936.png)

**Comment by SaeruHikari** [comment]
抱歉刚看到回复晚了。。。

https://github.com/SakuraEngine/Sakura.Resources/releases/tag/SDKs

![image](https://user-images.githubusercontent.com/39457738/186828644-47b8f039-2c22-44a0-ae6e-5ba0228db36d.png)

应该是有的，看下是不是 zip 损坏了？在 SDKs 文件夹下。也可以手动下载这个 zip 放进去。目前只有热更三角形的 demo 用到 wasm，其他的项目是不需要 m3 的。

**Comment by SaeruHikari** [comment]
https://github.com/SakuraEngine/Sakura.Runtime/pull/18

README中的手动构建缺失了这一行，补上即可
