### ISSUE TITLE
请问大佬构建的时候出现这样错误怎么解决？

### ISSUE THREAD

**Issue by happyxianyu** [SakuraEngine/Sakura.Runtime#2]
error: render-scene.cpp
。。。\include\scene.h(4): fatal error C1083: 无法打开包括文件: “GameRT/scene.dual.generated.hpp”: No such file or directory

**Comment by BenzzzX** [comment]
> error: render-scene.cpp
> 。。。\include\scene.h(4): fatal error C1083: 无法打开包括文件: “GameRT/scene.dual.generated.hpp”: No such file or directory
> 
> 

build/.gen里面有生成对应的文件吗？

**Comment by happyxianyu** [comment]
没有找到

**Comment by BenzzzX** [comment]
构建之前要先 xmake l setup.lua 解压一下 SDK，这一步有做吗

**Comment by happyxianyu** [comment]
有做

**Comment by happyxianyu** [comment]
xmake l setup.lua 
xmake b

**Comment by BenzzzX** [comment]
,gens 文件夹下面有生成 xxx.h.meta 这种文件吗，还有可能就是 python 执行失败了，目前好像 python 是静默执行的。。。
python 的前置条件是要安装 mako 这个包

**Comment by happyxianyu** [comment]
没有

**Comment by happyxianyu** [comment]
要不写个requiremets.txt吧

**Comment by BenzzzX** [comment]
稍后会加一个，现在正在整理工程结构，所以比较混乱

**Comment by happyxianyu** [comment]
还是不行

**Comment by BenzzzX** [comment]
完全没有生成 .gens 就不对劲了。。。有 build 的 log 吗，xmake b --verbose 输出一下？

**Comment by happyxianyu** [comment]
这个输出是我添加zlib依赖后的输出

**Comment by happyxianyu** [comment]
但还是有问题

**Comment by happyxianyu** [comment]
verbose输出最后是这样的：
error: render-scene.cpp
D:\tmp\Sakura.Runtime\samples\game\include\scene.h(4): fatal error C1083: 无法打开包括文件: “GameRT/scene.dual.generated.hpp”: No such file or directory

**Comment by happyxianyu** [comment]
我在尝试，现在不知道为什么又有找不到zlib.dll的问题了

**Comment by happyxianyu** [comment]
我重新安装一遍zlib又能找到zlib了，但删除.deps后就找不到zlib了

**Comment by happyxianyu** [comment]
checkinfo: runv(D:\tmp\Sakura.Runtime\SDKs\tools\windows\meta.exe --version) failed(-1073741515)
checkinfo: cannot runv(meta.exe --version), No such file or directory
checking for meta ... no

**Comment by happyxianyu** [comment]
但我检查了一下meta.exe是存在的，但是我手动执行了一下meta.exe --version，没有返回值

**Comment by happyxianyu** [comment]
准确说不是没有返回值，是没有输出信息

**Comment by happyxianyu** [comment]
可能还有一些值得关注的信息：
checkinfo: cannot runv(pkg-config.exe --version), No such file or directory
checking for pkg-config ... no
checkinfo: cannot runv(pkgconf.exe --version), No such file or directory
checking for pkgconf ... no

**Comment by happyxianyu** [comment]
那我再切clang试试

**Comment by BenzzzX** [comment]
正常的输出应该是
>meta.exe --version
  LLVM (http://llvm.org/):
  LLVM version 14.0.0git
  Optimized build.
  Default target: x86_64-pc-windows-msvc
  Host CPU: znver2

**Comment by happyxianyu** [comment]
不应该是损坏的问题吧，重试了很多次了
![image](https://user-images.githubusercontent.com/57778195/172653543-5e0e833a-331e-47b8-897f-3f37b5bd78cb.png)

**Comment by happyxianyu** [comment]
这是SDKs的目录

**Comment by BenzzzX** [comment]
不在这个仓库里，在这个组织下的 Sakura.Reflector 仓库里

**Comment by happyxianyu** [comment]
好吧我放弃了，需要llvm依赖，llvm编译实在痛苦

**Comment by BenzzzX** [comment]
留一下系统环境参数我参考一下吧，我手头没有能复现的环境比较难搞

**Comment by happyxianyu** [comment]
我的系统是win10的

**Comment by happyxianyu** [comment]
版本	Windows 10 家庭中文版
版本号	21H2
操作系统内部版本	19044.1706

WindowsSDKVersion=10.0.19041.0

**Comment by BenzzzX** [comment]
那你放一个 zlib.dll 到 PATH 包含的文件夹下或者直接放到 SDKs/tools/windows 目录下应该就行了

**Comment by happyxianyu** [comment]
我找找zlib.dll，不会是xmake的问题吧，没有给我编译为zlib.dll

**Comment by BenzzzX** [comment]
是 windows 的 dll 查询路径问题，是
1. 当前文件夹
2. 系统文件夹
3. PATH 引用的路径
因为 windows 没有好的 install 机制，所以很容易出这个问题，我明天把这个 dll 直接和 meta 打包到一起吧

**Comment by happyxianyu** [comment]
嗯，你弄好了，我再测试

**Comment by happyxianyu** [comment]
的确是zlib的问题，我手动编译了一个zlib.dll，放到meta.exe文件夹后再xmake b终于跑到99%了，但是又出现另一个问题，还是zlib的
[ 99%]: linking.release SkrCompiler.exe
error: @programdir\modules\private\async\runjobs.lua:232: @programdir\actions\build\kinds\binary.lua:74: @programdir\modules\core\tools\link.lua:159: LINK : fatal error LNK1181: 无法打开输入文件“zlibstatic.lib”

**Comment by BenzzzX** [comment]
啊这个是我compiler的grpc依赖没有清理干净，把xmake里面zlib那几行删了应该就可以了

**Comment by happyxianyu** [comment]
等一下，我又重新构建了一下，不知道为什么只能跑到95%了，提示
error: LINK : fatal error LNK1104: 无法打开文件“tbb.lib”

**Comment by BenzzzX** [comment]
USDTool 依赖了 usd，usd 目前是通过 vcpkg 安装的，这玩意非常大，建议先跳过这个。。。

**Comment by happyxianyu** [comment]
所以现在还是不能完全自动构建是吗？那有没有手动构建的方式？

**Comment by BenzzzX** [comment]
可以用 xmake b target 编译指定目标或者关掉参数 build_usdtool，如果你想要编译 usdtool 的话需要下载一个 vcpkg，然后配置上环境变量 VCPKG_ROOT，之后在仓库根目录执行一下 xmake require 安装依赖。

但是编译完之后要执行也还是会面临 dll 问题，这个只能手写 launch.json 解决了，我写了一个还没有同步上来。

**Comment by happyxianyu** [comment]
也许可以把dll都放在一个文件，然后运行时设置PATH变量就可以了

**Comment by happyxianyu** [comment]
launch.json是指vscode的launch.json吗？如果是的话，还可以在根目录写一个.env文件设置环境变量

**Comment by happyxianyu** [comment]
而且vscode也可以开发插件，但是会更麻烦些

**Comment by BenzzzX** [comment]
xmake 本身就自带一个插件倒是，后面可以考虑基于这个做点工作。。。

**Comment by BenzzzX** [comment]
更新了 SDKs 的内容，把 zlib.dll 和 meta.exe 打包在一起了，然后更新了一下 README 大概描述了一下构建。
