### ISSUE TITLE
macOS Monterey 运行Game失败

### ISSUE THREAD

**Issue by Lu-Kye** [SakuraEngine/Sakura.Runtime#3]
<img width="999" alt="image" src="https://user-images.githubusercontent.com/5763734/173965649-22cf5828-98da-4155-94c7-080c808a72ad.png">

Hi, 参考Readme中的编译命令编译通过了，环境安装应该也没什么问题，安装环境使用的命令如下:
brew install xmake
vcpkg 是从github上clone的源码，然后进行的本地编译 并配置了环境变量。
vcpkg install usd 
vcpkg install grpc
pip3 install mako
vulkan sdk是官网下载的macos installer文件

Result如上图: 
1. 直接运行./Game 程序报错 vulkan 初始化失败
2. 注释掉vulkan的宏 强制使用metal之后 也还是运行失败

**Comment by SaeruHikari** [comment]
Metal后端暂时还没有实现，mac上只能MoltenVK。我看一下Vulkan后端的代码定位一下问题。

**Comment by SaeruHikari** [comment]
- [ ]

**Comment by SaeruHikari** [comment]
Metal后端暂时还没有实现，mac上只能MoltenVK。我看一下Vulkan后端的代码定位一下问题。

**Comment by SaeruHikari** [comment]
添加了打印vulkan后端创建Instance失败时fatal code的代码，可以拉一下主干再跑一下vulkan后端看看log

**Comment by Lu-Kye** [comment]
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/5763734/173995308-34a45c42-bae2-4ea9-adc1-0a2711306207.png">

顺便想问下debug的环境是怎么配置的？

**Comment by SaeruHikari** [comment]
debug 直接用 VSCode 的 XMake 插件，插件集成了 debug launch 的功能。或者生成 VS 项目去调试。
看了下-9是 VK_ERROR_INCOMPATIBLE_DRIVER，很难进一步调试了，而且我本地的三台 mbp 尝试装了不同的 vk 版本都没法复现。可能还是要你进一步检查下本地环境。。。

**Comment by Lu-Kye** [comment]
试着去跑了下Vulkan-Samples这个开源项目，也是一样的createinstance fail.

**Comment by Lu-Kye** [comment]
哈喽 我把我本地的VulkanSDK 从最新的 1.3.216 降到 1.2.198.1 就可以了。。。

**Comment by SaeruHikari** [comment]
嗯解决了就好，可能Khronos的测试也没覆盖全。。。
